name: "[Reusable] Labeled Deployment"

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      prefix:
        type: string
        required: true

jobs:
  new-labeled-deployment:
    name: "Deployment"
    runs-on: ubuntu-latest
    steps:
      - run: |
          version="${head_ref/prefix/}"
          echo "Tag: ${version}"
          echo "Branch: ${branch}"
          echo "Prefix: ${prefix}"
          echo "Label: ${label}"
          echo "Head Ref: ${head_ref}"
          echo "Base Ref: ${base_ref}"
        env:
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          prefix: ${{ inputs.prefix }}
          branch: ${{ inputs.branch }}
          label: ${{ github.event.label.name }}