name: "[Reusable] Release"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  create-new-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create release branch
        run: git checkout -b release/v${{ inputs.version }}

      - name: Update version
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version
          git add package.json
          git commit --message "Prepare release v${{ inputs.version }}"
          git push --set-upstream origin release/v${{ inputs.version }}

      - name: Create pull request to `develop`
        run: |
          gh pr create --draft --base develop --title "Release v${{ inputs.version }} [develop]" --body ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
