name: "Create new hotfix"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-hotfix:
    uses: ./.github/workflows/new_hotfix
    with:
      version: ${{ github.event.inputs.version }}
      branch: main
