name: "Create new hotfix"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-hotfix:
    name: "New hotfix"
    uses: ./.github/workflows/new_hotfix.yml
    with:
      version: ${{ github.event.inputs.version }}
      main_branch: 'yes'
      rata_branch: 'yes'
      nikau_branch: 'no'