name: "Create new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-release:
    name: "New release"
    uses: ./.github/workflows/new_release.yml
    with:
      version: ${{ github.event.inputs.version }}
      main_branch: true