name: "Deploy"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        type: choice
        options:
          - main
          - nikau
          - rata

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: nicksnell/action-reset-repo@master
        with:
          base_branch: develop
          reset_branch: ${{ github.event.inputs.branch }}
