name: "Labeled Deployment"

on:
  pull_request:
    types:
      - labeled
    branches:
      - "develop"

jobs:
  deploy-rata:
    name: "Rata"
    if: ${{ github.event.label.name == 'deploy:rata' }}
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: rata
  deploy-nikau:
    name: "Nikau"
    if: ${{ github.event.label.name == 'deploy:nikau' }}
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: nikau
  deploy-main:
    name: "Main"
    if: ${{ github.event.label.name == 'deploy:main' }}
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: main