name: "Labeled Deployment"

on:
  pull_request:
    types:
      - labeled
    branches:
      - "develop"

jobs:
  deploy-rata:
    name: "Rata"
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: rata
  deploy-nikau:
    name: "Nikau"
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: nikau