name: "Labeled Deployment"

on:
  pull_request:
    types:
      - labeled
    branches:
      - "develop"

jobs:
  deploy-rata:
    name: "Rata"
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: rata
      prefix: "release/v"

  deploy-nikau:
    name: "Nikau"
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: nikau
      prefix: "release/v"

  deploy-main:
    name: "Mainnet"
    uses: ./.github/workflows/_labeled_deployment.yml
    with:
      branch: main
      prefix: "release/v"