name: "[Reusable] New Labeled Deployment"

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  new-labeled-deployment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.branch }}"
          echo "${{ github.event.label.name }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"