name: "New Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  create-new-release:
    name: "Create"
    uses: ./.github/workflows/reusable/release.yml
    with:
      version: ${{ github.event.inputs.version }}